title: Rob Hoelzle, PhD
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Bioinformatician
  <br><br>
  11 years’ experience in high paced R&D environment, 6 years’ experience in bioinformatics, and a life-long passion for problem solving. Proficient in Python, R, Bash, T-SQL, SQLite, ML & AI algorithms, multivariate statistics, creative problem solving, project management, consulting, and technical writing and communication
  <br><br>
  <a href="https://www.linkedin.com/in/robert-hoelzle/">LinkedIn</a>
  <br>
  <a href="https://scholar.google.com/citations?user=gcUZmB4AAAAJ&hl=en">Google Scholar</a>

theme: jekyll-theme-minimal
