title: Rob Hoelzle, PhD
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br>
  Bioinformatician 
  <br><br>
  <a href="https://www.linkedin.com/in/robert-hoelzle/">LinkedIn</a> 
  <br>
  <a href="https://scholar.google.com/citations?user=gcUZmB4AAAAJ&hl=en">Google Scholar</a>
  
theme: jekyll-theme-minimal
