title: Rob Hoelzle, PhD
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Engineer
  <br><br>
  8 years’ experience in big data analytics, 13 years’ experience in high paced R&D environment, and a life-long passion for problem solving
  <br><br>
  <a href="https://github.com/RDhoelzle">GitHub</a>
  <br>
  <a href="https://www.linkedin.com/in/robert-hoelzle/">LinkedIn</a>
  <br>
  <a href="https://scholar.google.com/citations?user=gcUZmB4AAAAJ&hl=en">Google Scholar</a>
  <br>
  <a href="https://www.credly.com/users/robert-hoelzle">Credly</a>
#<br><br>
#<a href="https://github.com/RDhoelzle/RDhoelzle.github.io/blob/master/pdf/CV_Robert_Hoelzle.pdf">View my CV</a>

theme: jekyll-theme-minimal
